/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parkingsystem;

import javax.swing.*;
import javax.swing.plaf.nimbus.State;
import javax.xml.transform.Result;
import java.awt.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Acer
 */
public class FourWheelerSlots extends javax.swing.JFrame {

    /**
     * Creates new form Slots
     */
    public FourWheelerSlots(String name, String number) {
        initComponents();
        namelabel.setText(name);
        numberlabel.setText(number);
        try{
            refreshSlots();
        }
        catch(Exception e){
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p1 = new java.awt.Panel();
        book1 = new javax.swing.JButton();
        release1 = new javax.swing.JButton();
        slot1 = new javax.swing.JLabel();
        p2 = new java.awt.Panel();
        book2 = new javax.swing.JButton();
        release2 = new javax.swing.JButton();
        slot2 = new javax.swing.JLabel();
        p3 = new java.awt.Panel();
        book3 = new javax.swing.JButton();
        release3 = new javax.swing.JButton();
        slot3 = new javax.swing.JLabel();
        p4 = new java.awt.Panel();
        book4 = new javax.swing.JButton();
        release4 = new javax.swing.JButton();
        slot4 = new javax.swing.JLabel();
        p5 = new java.awt.Panel();
        book5 = new javax.swing.JButton();
        release5 = new javax.swing.JButton();
        slot5 = new javax.swing.JLabel();
        p6 = new java.awt.Panel();
        book6 = new javax.swing.JButton();
        release6 = new javax.swing.JButton();
        slot6 = new javax.swing.JLabel();
        p12 = new java.awt.Panel();
        book12 = new javax.swing.JButton();
        release12 = new javax.swing.JButton();
        slot12 = new javax.swing.JLabel();
        p7 = new java.awt.Panel();
        book7 = new javax.swing.JButton();
        release7 = new javax.swing.JButton();
        slot7 = new javax.swing.JLabel();
        p8 = new java.awt.Panel();
        book8 = new javax.swing.JButton();
        release8 = new javax.swing.JButton();
        slot8 = new javax.swing.JLabel();
        p9 = new java.awt.Panel();
        book9 = new javax.swing.JButton();
        release9 = new javax.swing.JButton();
        slot9 = new javax.swing.JLabel();
        p10 = new java.awt.Panel();
        book10 = new javax.swing.JButton();
        release10 = new javax.swing.JButton();
        slot10 = new javax.swing.JLabel();
        p11 = new java.awt.Panel();
        book11 = new javax.swing.JButton();
        release11 = new javax.swing.JButton();
        slot11 = new javax.swing.JLabel();
        p18 = new java.awt.Panel();
        book18 = new javax.swing.JButton();
        release18 = new javax.swing.JButton();
        slot18 = new javax.swing.JLabel();
        p13 = new java.awt.Panel();
        book13 = new javax.swing.JButton();
        release13 = new javax.swing.JButton();
        slot13 = new javax.swing.JLabel();
        p16 = new java.awt.Panel();
        book16 = new javax.swing.JButton();
        release16 = new javax.swing.JButton();
        slot16 = new javax.swing.JLabel();
        p17 = new java.awt.Panel();
        book17 = new javax.swing.JButton();
        release17 = new javax.swing.JButton();
        slot17 = new javax.swing.JLabel();
        p14 = new java.awt.Panel();
        book14 = new javax.swing.JButton();
        release14 = new javax.swing.JButton();
        slot14 = new javax.swing.JLabel();
        p15 = new java.awt.Panel();
        book15 = new javax.swing.JButton();
        release15 = new javax.swing.JButton();
        slot15 = new javax.swing.JLabel();
        p19 = new java.awt.Panel();
        book19 = new javax.swing.JButton();
        release19 = new javax.swing.JButton();
        slot19 = new javax.swing.JLabel();
        p20 = new java.awt.Panel();
        book20 = new javax.swing.JButton();
        release20 = new javax.swing.JButton();
        slot20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numberlabel = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p1.setBackground(new java.awt.Color(255, 0, 0));

        book1.setText("Book");
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });

        release1.setText("Release");
        release1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release1ActionPerformed(evt);
            }
        });

        slot1.setText("1");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addComponent(release1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                                .addComponent(book1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                                .addComponent(slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))))))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addComponent(slot1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release1)
                .addGap(12, 12, 12))
        );

        p2.setBackground(new java.awt.Color(255, 0, 0));

        book2.setText("Book");
        book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book2ActionPerformed(evt);
            }
        });

        release2.setText("Release");
        release2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release2ActionPerformed(evt);
            }
        });

        slot2.setText("2");

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(release2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addComponent(slot2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release2)
                .addGap(12, 12, 12))
        );

        p3.setBackground(new java.awt.Color(255, 0, 0));

        book3.setText("Book");
        book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book3ActionPerformed(evt);
            }
        });

        release3.setText("Release");
        release3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release3ActionPerformed(evt);
            }
        });

        slot3.setText("3");

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(release3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addComponent(slot3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release3)
                .addGap(12, 12, 12))
        );

        p4.setBackground(new java.awt.Color(255, 0, 0));

        book4.setText("Book");
        book4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book4ActionPerformed(evt);
            }
        });

        release4.setText("Release");
        release4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release4ActionPerformed(evt);
            }
        });

        slot4.setText("4");

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addComponent(slot4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release4)
                .addGap(12, 12, 12))
        );

        p5.setBackground(new java.awt.Color(255, 0, 0));

        book5.setText("Book");
        book5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book5ActionPerformed(evt);
            }
        });

        release5.setText("Release");
        release5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release5ActionPerformed(evt);
            }
        });

        slot5.setText("5");

        javax.swing.GroupLayout p5Layout = new javax.swing.GroupLayout(p5);
        p5.setLayout(p5Layout);
        p5Layout.setHorizontalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(slot5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p5Layout.setVerticalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addComponent(slot5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release5)
                .addGap(12, 12, 12))
        );

        p6.setBackground(new java.awt.Color(255, 0, 0));

        book6.setText("Book");
        book6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book6ActionPerformed(evt);
            }
        });

        release6.setText("Release");
        release6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release6ActionPerformed(evt);
            }
        });

        slot6.setText("6");

        javax.swing.GroupLayout p6Layout = new javax.swing.GroupLayout(p6);
        p6.setLayout(p6Layout);
        p6Layout.setHorizontalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p6Layout.createSequentialGroup()
                .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p6Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        p6Layout.setVerticalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p6Layout.createSequentialGroup()
                .addComponent(slot6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release6)
                .addGap(12, 12, 12))
        );

        p12.setBackground(new java.awt.Color(255, 0, 0));

        book12.setText("Book");
        book12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book12ActionPerformed(evt);
            }
        });

        release12.setText("Release");
        release12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release12ActionPerformed(evt);
            }
        });

        slot12.setText("12");

        javax.swing.GroupLayout p12Layout = new javax.swing.GroupLayout(p12);
        p12.setLayout(p12Layout);
        p12Layout.setHorizontalGroup(
            p12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p12Layout.createSequentialGroup()
                .addGroup(p12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p12Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(slot12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        p12Layout.setVerticalGroup(
            p12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p12Layout.createSequentialGroup()
                .addComponent(slot12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release12)
                .addGap(12, 12, 12))
        );

        p7.setBackground(new java.awt.Color(255, 0, 0));

        book7.setText("Book");
        book7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book7ActionPerformed(evt);
            }
        });

        release7.setText("Release");
        release7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release7ActionPerformed(evt);
            }
        });

        slot7.setText("7");

        javax.swing.GroupLayout p7Layout = new javax.swing.GroupLayout(p7);
        p7.setLayout(p7Layout);
        p7Layout.setHorizontalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p7Layout.createSequentialGroup()
                .addGroup(p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(book7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p7Layout.createSequentialGroup()
                        .addGroup(p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(release7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p7Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(slot7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p7Layout.setVerticalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p7Layout.createSequentialGroup()
                .addComponent(slot7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release7)
                .addGap(12, 12, 12))
        );

        p8.setBackground(new java.awt.Color(255, 0, 0));

        book8.setText("Book");
        book8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book8ActionPerformed(evt);
            }
        });

        release8.setText("Release");
        release8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release8ActionPerformed(evt);
            }
        });

        slot8.setText("8");

        javax.swing.GroupLayout p8Layout = new javax.swing.GroupLayout(p8);
        p8.setLayout(p8Layout);
        p8Layout.setHorizontalGroup(
            p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p8Layout.createSequentialGroup()
                .addGroup(p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p8Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(slot8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        p8Layout.setVerticalGroup(
            p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p8Layout.createSequentialGroup()
                .addComponent(slot8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release8)
                .addGap(12, 12, 12))
        );

        p9.setBackground(new java.awt.Color(255, 0, 0));

        book9.setText("Book");
        book9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book9ActionPerformed(evt);
            }
        });

        release9.setText("Release");
        release9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release9ActionPerformed(evt);
            }
        });

        slot9.setText("9");

        javax.swing.GroupLayout p9Layout = new javax.swing.GroupLayout(p9);
        p9.setLayout(p9Layout);
        p9Layout.setHorizontalGroup(
            p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p9Layout.createSequentialGroup()
                .addGroup(p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p9Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(slot9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p9Layout.setVerticalGroup(
            p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p9Layout.createSequentialGroup()
                .addComponent(slot9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release9)
                .addGap(12, 12, 12))
        );

        p10.setBackground(new java.awt.Color(255, 0, 0));

        book10.setText("Book");
        book10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book10ActionPerformed(evt);
            }
        });

        release10.setText("Release");
        release10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release10ActionPerformed(evt);
            }
        });

        slot10.setText("10");

        javax.swing.GroupLayout p10Layout = new javax.swing.GroupLayout(p10);
        p10.setLayout(p10Layout);
        p10Layout.setHorizontalGroup(
            p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p10Layout.createSequentialGroup()
                .addGroup(p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p10Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(slot10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        p10Layout.setVerticalGroup(
            p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p10Layout.createSequentialGroup()
                .addComponent(slot10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release10)
                .addGap(12, 12, 12))
        );

        p11.setBackground(new java.awt.Color(255, 0, 0));

        book11.setText("Book");
        book11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book11ActionPerformed(evt);
            }
        });

        release11.setText("Release");
        release11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release11ActionPerformed(evt);
            }
        });

        slot11.setText("11");

        javax.swing.GroupLayout p11Layout = new javax.swing.GroupLayout(p11);
        p11.setLayout(p11Layout);
        p11Layout.setHorizontalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p11Layout.createSequentialGroup()
                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p11Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(slot11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p11Layout.setVerticalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p11Layout.createSequentialGroup()
                .addComponent(slot11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release11)
                .addGap(12, 12, 12))
        );

        p18.setBackground(new java.awt.Color(255, 0, 0));

        book18.setText("Book");
        book18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book18ActionPerformed(evt);
            }
        });

        release18.setText("Release");
        release18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release18ActionPerformed(evt);
            }
        });

        slot18.setText("18");

        javax.swing.GroupLayout p18Layout = new javax.swing.GroupLayout(p18);
        p18.setLayout(p18Layout);
        p18Layout.setHorizontalGroup(
            p18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p18Layout.createSequentialGroup()
                .addGroup(p18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p18Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release18, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book18, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p18Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(slot18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        p18Layout.setVerticalGroup(
            p18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p18Layout.createSequentialGroup()
                .addComponent(slot18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release18)
                .addGap(12, 12, 12))
        );

        p13.setBackground(new java.awt.Color(255, 0, 0));

        book13.setText("Book");
        book13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book13ActionPerformed(evt);
            }
        });

        release13.setText("Release");
        release13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release13ActionPerformed(evt);
            }
        });

        slot13.setText("13");

        javax.swing.GroupLayout p13Layout = new javax.swing.GroupLayout(p13);
        p13.setLayout(p13Layout);
        p13Layout.setHorizontalGroup(
            p13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p13Layout.createSequentialGroup()
                .addGroup(p13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p13Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(book13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p13Layout.createSequentialGroup()
                        .addGroup(p13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p13Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(release13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p13Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(slot13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p13Layout.setVerticalGroup(
            p13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p13Layout.createSequentialGroup()
                .addComponent(slot13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release13)
                .addGap(12, 12, 12))
        );

        p16.setBackground(new java.awt.Color(255, 0, 0));

        book16.setText("Book");
        book16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book16ActionPerformed(evt);
            }
        });

        release16.setText("Release");
        release16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release16ActionPerformed(evt);
            }
        });

        slot16.setText("16");

        javax.swing.GroupLayout p16Layout = new javax.swing.GroupLayout(p16);
        p16.setLayout(p16Layout);
        p16Layout.setHorizontalGroup(
            p16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p16Layout.createSequentialGroup()
                .addGroup(p16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release16, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book16, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p16Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(slot16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        p16Layout.setVerticalGroup(
            p16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p16Layout.createSequentialGroup()
                .addComponent(slot16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release16)
                .addGap(12, 12, 12))
        );

        p17.setBackground(new java.awt.Color(255, 0, 0));

        book17.setText("Book");
        book17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book17ActionPerformed(evt);
            }
        });

        release17.setText("Release");
        release17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release17ActionPerformed(evt);
            }
        });

        slot17.setText("17");

        javax.swing.GroupLayout p17Layout = new javax.swing.GroupLayout(p17);
        p17.setLayout(p17Layout);
        p17Layout.setHorizontalGroup(
            p17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p17Layout.createSequentialGroup()
                .addGroup(p17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release17, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book17, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p17Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(slot17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p17Layout.setVerticalGroup(
            p17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p17Layout.createSequentialGroup()
                .addComponent(slot17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release17)
                .addGap(12, 12, 12))
        );

        p14.setBackground(new java.awt.Color(255, 0, 0));

        book14.setText("Book");
        book14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book14ActionPerformed(evt);
            }
        });

        release14.setText("Release");
        release14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release14ActionPerformed(evt);
            }
        });

        slot14.setText("14");

        javax.swing.GroupLayout p14Layout = new javax.swing.GroupLayout(p14);
        p14.setLayout(p14Layout);
        p14Layout.setHorizontalGroup(
            p14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p14Layout.createSequentialGroup()
                .addGroup(p14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release14, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book14, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p14Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(slot14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        p14Layout.setVerticalGroup(
            p14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p14Layout.createSequentialGroup()
                .addComponent(slot14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release14)
                .addGap(12, 12, 12))
        );

        p15.setBackground(new java.awt.Color(255, 0, 0));

        book15.setText("Book");
        book15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book15ActionPerformed(evt);
            }
        });

        release15.setText("Release");
        release15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release15ActionPerformed(evt);
            }
        });

        slot15.setText("15");

        javax.swing.GroupLayout p15Layout = new javax.swing.GroupLayout(p15);
        p15.setLayout(p15Layout);
        p15Layout.setHorizontalGroup(
            p15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p15Layout.createSequentialGroup()
                .addGroup(p15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p15Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(slot15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p15Layout.setVerticalGroup(
            p15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p15Layout.createSequentialGroup()
                .addComponent(slot15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release15)
                .addGap(12, 12, 12))
        );

        p19.setBackground(new java.awt.Color(255, 0, 0));

        book19.setText("Book");
        book19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book19ActionPerformed(evt);
            }
        });

        release19.setText("Release");
        release19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release19ActionPerformed(evt);
            }
        });

        slot19.setText("19");

        javax.swing.GroupLayout p19Layout = new javax.swing.GroupLayout(p19);
        p19.setLayout(p19Layout);
        p19Layout.setHorizontalGroup(
            p19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p19Layout.createSequentialGroup()
                .addGroup(p19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p19Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release19, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book19, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p19Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(slot19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p19Layout.setVerticalGroup(
            p19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p19Layout.createSequentialGroup()
                .addComponent(slot19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release19)
                .addGap(12, 12, 12))
        );

        p20.setBackground(new java.awt.Color(255, 0, 0));

        book20.setText("Book");
        book20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book20ActionPerformed(evt);
            }
        });

        release20.setText("Release");
        release20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release20ActionPerformed(evt);
            }
        });

        slot20.setText("20");

        javax.swing.GroupLayout p20Layout = new javax.swing.GroupLayout(p20);
        p20.setLayout(p20Layout);
        p20Layout.setHorizontalGroup(
            p20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p20Layout.createSequentialGroup()
                .addGroup(p20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p20Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(release20, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book20, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p20Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(slot20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p20Layout.setVerticalGroup(
            p20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p20Layout.createSequentialGroup()
                .addComponent(slot20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(release20)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(p14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Four Wheeler Parking Slots");

        jLabel2.setText("Hello, ");

        jLabel3.setText("Your vehicle number is  ->");

        logoutbtn.setText("LOGOUT");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namelabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberlabel)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(logoutbtn))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namelabel)
                    .addComponent(jLabel3)
                    .addComponent(numberlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void refreshSlots() throws Exception{
        Connection con=RegisterDriver.connect();
        Panel[] panels={p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20};
        JButton[] bookbuttons={book1,book2,book3,book4,book5,book6,book7,book8,book9,book10,book11,book12,book13,book14,book15,book16,book17,book18,book19,book20};
        JButton[] releasebuttons={release1,release2,release3,release4,release5,release6,release7,release8,release9,release10,release11,release12,release13,release14,release15,release16,release17,release18,release19,release20};
        for(int i=1;i<=20;i++){
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select book_status from fourwheelerslot where slotnum="+i+";");
            rs.next();
            if(rs.getString(1).equals("true")){
                bookbuttons[i-1].setEnabled(false);
                releasebuttons[i-1].setEnabled(true);
                panels[i-1].setBackground(Color.green);
            }
            else if(rs.getString(1).equals("false")){
                bookbuttons[i-1].setEnabled(true);
                releasebuttons[i-1].setEnabled(false);
                panels[i-1].setBackground(Color.red);
            }
        }
    }

    public void bookSlot(int slot, String name, String number) throws Exception{
        Connection con = RegisterDriver.connect();
        Statement stmt = con.createStatement();
        stmt.executeUpdate("update fourwheelerslot set book_status='true', owner_name='"+name+"', vehicle_number='"+number+"' where slotnum=" + slot + ";");
        JOptionPane.showMessageDialog(this, "Slot no. " + slot + " booked successfully");
        refreshSlots();
    }

    public void releaseSlot(int slot, String name, String number) throws Exception{
        Connection con = RegisterDriver.connect();
        Statement stmt1=con.createStatement();
        ResultSet rs=stmt1.executeQuery("select owner_name,vehicle_number from fourwheelerslot where slotnum="+slot+";");
        rs.next();
        if(name.equals(rs.getString(1)) && number.equals(rs.getString(2))) {
            Statement stmt = con.createStatement();
            stmt.executeUpdate("update fourwheelerslot set book_status='false', owner_name=null, vehicle_number=null where slotnum=" + slot + ";");
            JOptionPane.showMessageDialog(this, "Slot no. " + slot + " released successfully");
            refreshSlots();
        }
        else{
            JOptionPane.showMessageDialog(this,"Sorry you can't release the slot,\nbecause, You are not the owner of this vehicle.");
        }
    }
    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot1.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book1ActionPerformed

    private void release1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release1ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot1.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release1ActionPerformed

    private void book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book2ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot2.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book2ActionPerformed

    private void release2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release2ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot2.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release2ActionPerformed

    private void book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book3ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot3.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book3ActionPerformed

    private void release3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release3ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot3.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release3ActionPerformed

    private void book4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book4ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot4.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book4ActionPerformed

    private void release4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release4ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot4.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release4ActionPerformed

    private void book5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book5ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot5.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book5ActionPerformed

    private void release5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release5ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot5.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release5ActionPerformed

    private void book6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book6ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot6.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book6ActionPerformed

    private void release6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release6ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot6.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release6ActionPerformed

    private void book12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book12ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot12.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book12ActionPerformed

    private void release12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release12ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot12.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release12ActionPerformed

    private void book7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book7ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot7.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book7ActionPerformed

    private void release7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release7ActionPerformed
        // TODO add your handling code here
        try {
            releaseSlot(Integer.parseInt(slot7.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }    }//GEN-LAST:event_release7ActionPerformed

    private void book8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book8ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot8.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book8ActionPerformed

    private void release8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release8ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot8.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release8ActionPerformed

    private void book9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book9ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot9.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book9ActionPerformed

    private void release9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release9ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot9.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release9ActionPerformed

    private void book10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book10ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot10.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book10ActionPerformed

    private void release10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release10ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot10.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release10ActionPerformed

    private void book11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book11ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot11.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book11ActionPerformed

    private void release11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release11ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot11.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release11ActionPerformed

    private void book18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book18ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot18.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book18ActionPerformed

    private void release18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release18ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot18.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release18ActionPerformed

    private void book13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book13ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot13.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book13ActionPerformed

    private void release13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release13ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot13.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release13ActionPerformed

    private void book16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book16ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot16.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book16ActionPerformed

    private void release16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release16ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot16.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release16ActionPerformed

    private void book17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book17ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot17.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book17ActionPerformed

    private void release17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release17ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot17.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release17ActionPerformed

    private void book14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book14ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot14.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book14ActionPerformed

    private void release14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release14ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot14.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release14ActionPerformed

    private void book15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book15ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot15.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book15ActionPerformed

    private void release15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release15ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot15.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release15ActionPerformed

    private void book19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book19ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot19.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book19ActionPerformed

    private void release19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release19ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot19.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release19ActionPerformed

    private void book20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book20ActionPerformed
        // TODO add your handling code here:
        try {
            bookSlot(Integer.parseInt(slot20.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_book20ActionPerformed

    private void release20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release20ActionPerformed
        // TODO add your handling code here:
        try {
            releaseSlot(Integer.parseInt(slot20.getText()),namelabel.getText(),numberlabel.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_release20ActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        LoginPage loginPage=new LoginPage();
        this.setVisible(false);
        loginPage.setVisible(true);
        loginPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_logoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FourWheelerSlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FourWheelerSlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FourWheelerSlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FourWheelerSlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton book1;
    private javax.swing.JButton book10;
    private javax.swing.JButton book11;
    private javax.swing.JButton book12;
    private javax.swing.JButton book13;
    private javax.swing.JButton book14;
    private javax.swing.JButton book15;
    private javax.swing.JButton book16;
    private javax.swing.JButton book17;
    private javax.swing.JButton book18;
    private javax.swing.JButton book19;
    private javax.swing.JButton book2;
    private javax.swing.JButton book20;
    private javax.swing.JButton book3;
    private javax.swing.JButton book4;
    private javax.swing.JButton book5;
    private javax.swing.JButton book6;
    private javax.swing.JButton book7;
    private javax.swing.JButton book8;
    private javax.swing.JButton book9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel numberlabel;
    private java.awt.Panel p1;
    private java.awt.Panel p10;
    private java.awt.Panel p11;
    private java.awt.Panel p12;
    private java.awt.Panel p13;
    private java.awt.Panel p14;
    private java.awt.Panel p15;
    private java.awt.Panel p16;
    private java.awt.Panel p17;
    private java.awt.Panel p18;
    private java.awt.Panel p19;
    private java.awt.Panel p2;
    private java.awt.Panel p20;
    private java.awt.Panel p3;
    private java.awt.Panel p4;
    private java.awt.Panel p5;
    private java.awt.Panel p6;
    private java.awt.Panel p7;
    private java.awt.Panel p8;
    private java.awt.Panel p9;
    private javax.swing.JButton release1;
    private javax.swing.JButton release10;
    private javax.swing.JButton release11;
    private javax.swing.JButton release12;
    private javax.swing.JButton release13;
    private javax.swing.JButton release14;
    private javax.swing.JButton release15;
    private javax.swing.JButton release16;
    private javax.swing.JButton release17;
    private javax.swing.JButton release18;
    private javax.swing.JButton release19;
    private javax.swing.JButton release2;
    private javax.swing.JButton release20;
    private javax.swing.JButton release3;
    private javax.swing.JButton release4;
    private javax.swing.JButton release5;
    private javax.swing.JButton release6;
    private javax.swing.JButton release7;
    private javax.swing.JButton release8;
    private javax.swing.JButton release9;
    private javax.swing.JLabel slot1;
    private javax.swing.JLabel slot10;
    private javax.swing.JLabel slot11;
    private javax.swing.JLabel slot12;
    private javax.swing.JLabel slot13;
    private javax.swing.JLabel slot14;
    private javax.swing.JLabel slot15;
    private javax.swing.JLabel slot16;
    private javax.swing.JLabel slot17;
    private javax.swing.JLabel slot18;
    private javax.swing.JLabel slot19;
    private javax.swing.JLabel slot2;
    private javax.swing.JLabel slot20;
    private javax.swing.JLabel slot3;
    private javax.swing.JLabel slot4;
    private javax.swing.JLabel slot5;
    private javax.swing.JLabel slot6;
    private javax.swing.JLabel slot7;
    private javax.swing.JLabel slot8;
    private javax.swing.JLabel slot9;
    // End of variables declaration//GEN-END:variables
}
